### ISSUE TITLE
Release / pre-built binaries

### ISSUE THREAD

**Issue by MaxGyver83** [slotThe/duden#1]
This looks like a cool project! Could you create a release and upload a binary (at least for the system you are using yourself, for non-Haskell developers)?

**Comment by slotThe** [comment]
Wow, I didn't expect anyone to care about this... every, really!  Just a warning: this has never been used by any person but myself (plus, duden.de doesn't have an API and so it's all scraped)—bugs galore, probably :)

I tried my best and it seems like I could actually produce a proper statically linked executable; you can find it [here](https://github.com/slotThe/duden/releases/download/v0.1.0/duden).  Let me know if I did something wrong and it doesn't work!

**Comment by MaxGyver83** [comment]
Nice, it works! Thank you!
